### ISSUE TITLE
Fetching dependencies from git

### ISSUE THREAD

**Issue by danlamanna** [emacs-eldev/eldev#91] opened 2023-07-11 01:40 UTC
I have a fairly simple project that I would like to set up that requires a dependency that isn't hosted on a package manager. It seems this is becoming more common as people use `straight` and `package-vc-install` to install directly. Is it possible to declare such a dependency in eldev given that it's not on a package manager or on a local path?

**Comment by doublep** [comment] 2023-07-11 17:02
No, it's currently not possible, but I long have thought about adding a plugin (i.e. optional extension) to Eldev that would do just this, probably using `straight`. If you could specify in more details what you'd need, I could have a look and maybe implement this in 1.5, the next version.

**Comment by danlamanna** [comment] 2023-07-15 19:17
I'd like the functionality and bootstrapping that's available to `eldev-use-local-dependency` but with an external git repo that can be pulled from a host. Whether it uses the spec format from `package-vc.el` or `straight.el` doesn't make a big difference to me.

**Comment by doublep** [comment] 2023-07-16 19:13
A problem here is that I have never used such functionality. I basically understand what you need and why, and I see how it would be a useful addition to Eldev too. But to design a good and usable interface I'd rather first see some real-world examples. If possible (i.e. not a private project), please provide a link to the outer project and the dependency. If not, at least show some code how you would use it, especially how you autofetch it from Git it in your normal Emacs — I assume you already do that.

**Comment by doublep** [comment] 2024-01-18 21:48
Hm, I just looked at the docstring of `use-package` and it doesn't mention `:vc`, at least in the version I have (2.4.5). Is it new? Is it built-in in `use-package`, or does it need something else?

**Comment by doublep** [comment] 2024-01-19 13:21
I see. So, basically, if Eldev was to support this, in project's file `Eldev` you would somehow specify where (and maybe how) to get certain dependencies. Something like:

    (eldev-fetch-package-from 'abc                             ; dependency package name
                              "https://github.com/abc.el/abc"  ; the URL
                              ; possible additional options, e.g. :fetcher 'git
                              )

And then when it needs to install dependency X, it first checks if it has a URL for it. If it does, fetch (via Git or whatever) from that URL, else fall back to the usual PA lookup. (Internally this could be implemented via some existing tool or not, don't know yet.)

Is that the desired mechanism? This means you'd have to enumerate all dependencies not available in package archives (MELPA or something) together with their URL. On the other hand, there is probably no way to look up "canonical repository URL for Elisp package named X", so you do have to specify it manually...

**Comment by doublep** [comment] 2024-11-01 20:05
Let's suppose your `project-x` declares that dependency `libfoo` must be fetched from certain Git repository. If `libfoo` itself depends on `libbar`, how should Eldev find that package?

Probably an option would be that `libbar` is to be looked up in archives that `project-x` itself declares. Or do you have a better idea?

**Comment by d12frosted** [comment] 2024-11-04 11:00
> If libfoo itself depends on libbar, how should Eldev find that package?

I think Eldev should not treat `libbar` in any special way. It's just a transitive dependency. Try to fetch it based on `Eldev` file of the `project-x` and if this transient dependency can not be satisfied - let the user explicitly either add a proper archive or declare from which repository to fetch. 

> If libfoo uses Eldev itself, perhaps it may help to use that dependency information.

If it's just to get dependency information, I am against this idea as it would complicate things both implementation and usage-wise. Since Eldev is a build tool, the only meaningful solution here is to build differently depending on existence of Eldev file - but do it in an 'isolated' way, i.e. without polluting and messing around with `project-x` configurations. 

> I believe if that's the only thing that is implemented, that it would be

I agree, just an ability to pull dependencies from Git would be a HUGE improvement. It would unblock me from using Eldev in all scenarios that I have.

**Comment by doublep** [comment] 2024-12-07 20:25
Finally committed some basic implementation. There are likely still many bugs, so I don't plan to release in the next days yes. Testing is certainly welcome (use `eldev --unstable upgrade-self`).

Basic usage: add sth. like

    (eldev-use-vc-repository 'mylib :git "CLONE-FROM")

or

    (eldev-use-vc-repository 'mylib :github "USER/REPO")

to file `Eldev`. Everything else should work as with regular dependencies. Note that like regular dependencies, VC/Git-based ones are not upgraded automatically. You need to run `eldev upgrade` manually.

Git dependencies are currently not inherited, so if your library uses one, the project needs to redeclare it. May add inheritance before 1.11.

**Comment by doublep** [comment] 2024-12-09 19:17
They are independent.

`eldev-use-vc-dependecy` is comparable to `eldev-use-package-archive` in that it tells Eldev how to find packages (former: one specific package in the given Git repository; latter: in a package archive, whatever its contents is). They both don't tell anything about what you need the packages for.

For that, packages must be declared as dependencies in project headers (in your main `.el` file or `*-pkg.el`). Or they can be listed in `eldev-add-extra-dependencies`. For this aspect there are no changes.

**Comment by doublep** [comment] 2024-12-09 20:21
Actually, now that I think of it, `...-use-vc-repository` would be a better name (and more similar to `...-use-package-archive`), since it doesn't _itself_ declare that it will necessary be a dependency. It's certainly still possible to rename, since there is no stable release with this functionality. What do you think?

**Comment by doublep** [comment] 2024-12-10 20:46
That's why I don't want to release yet: fixed _three_ different bugs as a result.

After the fixes, in `git-email` I added these two lines:

    (eldev-use-vc-repository 'piem :git "https://git.kyleam.com/piem")
    (eldev-add-extra-dependencies '(build eval emacs) 'piem)

This still results in an error, but this time the problem is in `piem` (or rather its infrastructure): Eldev doesn't know how to build a package from it, because the project doesn't tell it:

    $ eldev eval 1
    [1/0] Installing package ‘piem’ (0.5.0.20241204.112) from ‘https://git.kyleam.com/piem’...
    Dependency ‘transient’ is not available
    Required by package ‘piem’
    There is no file ‘Eldev’ in the project; consider running ‘eldev init’
    Child Eldev process for VC-fetched package ‘piem’ exited with error code 1
    Failed step: installing dependency package ‘piem’

I could resolve that by effectively providing Eldev settings for `piem` from `git-email` like this:

    (eldev-use-vc-repository 'piem :git "https://git.kyleam.com/piem"
                             :setup '(eldev-use-package-archive 'gnu-elpa))

You can instead make `piem` buildable with Eldev directly, then `git-email` won't have to provide the setup form for it.

**Comment by doublep** [comment] 2024-12-11 18:07
I don't plan to support its syntax.

> :lisp-dir "./mu4e"

If it means what I think it means, you can include `(setf eldev-project-source-dirs "mu4e")` into the `:setup` form. If you need to combine several setup forms, just use `progn`.

> :rev "v1.12.7"

What does that mean?

Currently `...-use-vc-repository` uses `HEAD` and treats it like a snapshot build by appending commit timestamp to the version. I plan to add optional handling of tagged (like what MELPA uses) stable builds.

**Comment by doublep** [comment] 2024-12-11 20:27
> A revision could be a git commit or a git tag. This in addition to the :branch (which defaults to the HEAD of said branch) allows one to check out a specific version of the dependency.
>
> Hopefully something like that would be supported.

What do you need this for? It's probably not difficult to support, but I don't understand the need for it. Normal users of your project will not be limited by your decision to use a specific version of a dependency, they will use the latest overall (snapshot) or the latest released (stable) version.

Elisp package archives, for example, don't give you access to old releases at all, so Eldev cannot support that in that case in principle. With Git repositories it could, but why should it be different?

> Hm I'm unable to get this to work. I've pushed the related change to git-email's dev branch.

I have a branch named `future-doc` and I have some documentation for this `...-use-vc-repository` there already. Check it out if you can. For example, here is what paragraph about `:setup` says:

> This form will be given to child Eldev processes whenever a package needs to be created out of the VC-fetched project. Most likely you will need to tell child Eldev how to locate dependencies of that project. The best way to figure it out is to check out the repository and create file Eldev in it with required contents (eldev init might help). Instead of committing the created file, convert its contents into an Elisp form (use progn if needed) and pass it as a value of :setup in your main project.

I suggest you try "the best way" outlined above yourself first. Basically, make `mu4e` buildable (`eldev package`) with Eldev. You cannot commit your work, but you can directly convert produced `Eldev` file into a setup form and include said form into _your_ project's `Eldev`.

**Comment by doublep** [comment] 2024-12-14 18:35
> Some users may also use specific releases. I am one such user.

OK, I added this feature. Pass `:commit "..."` to `eldev-use-vc-repository` (can be a tag name or a _full_ Git commit hash).

> Noted. That's a sensible approach.

Any success with that?

**Comment by doublep** [comment] 2024-12-15 10:29
Eldev is targeted at Elisp, but it is possible to include other steps into build process. For example [`datetime`](https://github.com/doublep/datetime) builds some Java tools. It might be easier not to compile every single `.cpp` file separately, but e.g. call `make` or whatever they use to build the whole codebase at once.

**Comment by doublep** [comment] 2024-12-16 19:06
I now consider this done. Maybe optional dependency inheritance could be added, but I'd prefer to do it separately later. Do you still have any specific issues with the functionality?

**Closed** 2024-12-17 12:38 UTC
Labels: enhancement

**Comment by d12frosted** [comment] 2025-01-23 20:35
Wow! Just gave it a try and it works like magic! Thanks a lot of implementing this feature! Now I can use Eldev with my unpublished packages ❤
