### ISSUE TITLE
Let user choose whether development tools are fetched from an archive or provided via the load-path

### ISSUE THREAD

**Issue by suhail-singh** [emacs-eldev/eldev#99] opened 2024-01-25 20:52 UTC
When building and testing a package in certain environments without network
access (e.g. when building packages in the Guix package manager), one may wish
to manually provide certain dependencies like test-frameworks.

For instance, [the `ox-tufte` package](https://github.com/ox-tufte/ox-tufte)
uses both `ert` and `buttercup` test frameworks.  When `eldev test` for this
package is invoked where the `buttercup` dependency is available in the
[`EMACSLOADPATH`](https://www.gnu.org/software/emacs/manual/html_node/emacs/General-Variables.html#index-EMACSLOADPATH_002c-environment-variable),
Eldev still tries to fetch `buttercup` from `melpa`.  When this action is
performed in the Guix build environment (where there is no network access) the
process fails.  For completeness, even `eldev test-ert` fails for this package
because `eldev-test-framework` specifies `'(ert buttercup)` and so an attempt to
fetch `buttercup` is made regardless.  When `buttercup` is removed from
`eldev-test-framework`, then `eldev test-ert` works.

The desired workflow is one where the user ensures that the development tool is
available in the `load-path` (by way of `EMACSLOADPATH` or otherwise), and
passes a commandline argument to `eldev` instructing it to not fetch the
development tool from the archive(s).  Is this possible to do in the current
version of Eldev?  If so, could you please point me in the right direction?  If
not, could this feature please be added?

~~On a related note, is there a way to work around the current limitation (should
it not simply be a result of my lack of awareness) by adding some code to the
project-specific `Eldev` file?~~

**Comment by doublep** [comment] 2024-01-26 09:48
This looks pretty similar to #64. As suggested there, you could either use global option `--external-deps` to take preinstalled packages (e.g. from the normal Emacs installation) or local dependencies if you want to make something not fetched over internet selectively. Would that be enough in your usecase?

**Comment by doublep** [comment] 2024-01-26 17:12
> might be sufficient, but inconvenient

Well, it would also be very inconvenient for Eldev to try and support yet another way of looking up dependencies. Please see [the comment in #64](https://github.com/emacs-eldev/eldev/issues/64#issuecomment-1004279511) that explains why supporting `load-path` is difficult and goes against how dependencies are looked up by Eldev.

> The environment variable EMACSLOADPATH is dynamically set at build time - the developer specifies the package dependencies and Guix ensures that the location of said dependencies is listed in $EMACSLOADPATH.

Who does that? Do you have any control over the code that sets the environment variable (and are you thus able to adjust it), or do you have to accept it like it is?

> (dolist (entry (split-string (getenv "EMACSLOADPATH") ":" t))
>   (ignore-errors ;; Eldev errors if local dependency is the package being built
>     (eldev-use-local-dependency entry)))

Well, that looks like a sane piece of code. Using full-fledged Elisp in setup files _is_ supposed to be Eldev feature. Instead of using `ignore-errors`, I would compare `entry` against `eldev-project-dir` using `file-equal-p` to avoid hiding other potential errors.

As an additional minor advantage, you can pass whatever `loading-mode` parameter to `eldev-use-local-dependency`.

**Comment by doublep** [comment] 2024-02-15 20:20
In 1.9 there will be `--disable-dependencies` (alias: `--use-emacsloadpath`; no short variant). Please test if that's what you need. As currently implemented, you need to include everything in `EMACSLOADPATH`, even the current directory.

**Comment by doublep** [comment] 2024-02-17 10:31
Yes, it is committed. You can also test it via standard installation after
running

    $ eldev  --unstable upgrade-self

You can later switch back to the released version by using

    $ eldev upgrade-self -d

Paul

**Comment by doublep** [comment] 2024-02-17 17:28
I guess this means that Eldev still needs to add the current directory to
`load-path'. I presumed that I could use the value set via EMACSLOADPATH
completely as-is.

To confirm, can you run e.g.:

    $ eldev --use-emacsloadpath eval --dont-require load-path

and tell me what it prints out?

Paul

**Comment by doublep** [comment] 2024-02-17 19:54
Ah, you are right, I didn't pay enough attention to the error message. It
seems like it's caused by `eldev--unload-package', and I need to remember
first what it's for.

Speaking of which, is there a way I could test this myself? E.g. some
Docker image or something? Would be much easier than going back and forth
with "please try now".

Paul

**Comment by doublep** [comment] 2024-02-18 11:27
I looked close to it now. The problem is with building and requiring
autoloads, in the project itself and its dependencies. Since this heavily
depends on the normal dependency-as-package management, it gets broken if
those are disabled. The easiest workaround, of course, is to completely
turn autoload handling off when using `--disable-dependencies' and just
document it like that. After all, this new option is only supposed to be
"for special needs", not something recommended for normal use.

Would it be fine for you, or do you *need* autoloads, e.g. during testing,
when running on Guix too?

Paul

**Comment by doublep** [comment] 2024-02-18 17:11
They wouldn't be generated and wouldn't take any effect, unlike with normal
Eldev operation. You would need to explicitly require the feature declaring
a function before calling it, even if the function was declared as
`###autoload'.

Paul

**Comment by doublep** [comment] 2024-02-19 18:56
Please test after commit be713dd.

Paul

**Comment by doublep** [comment] 2024-03-04 20:33
Sorry, I was busy with unrelated things and then forgot about this issue. Before releasing 1.9 I want to figure out the problems in #100, but there are no other plans.

**Comment by doublep** [comment] 2024-03-05 22:23
Released 1.9 with the new option.

**Closed by doublep** 2024-03-05 22:23 UTC
Labels: enhancement
